### PR TITLE
Avoiding confusing between Blender X axis and Threejs Y Axis

### PR DESCRIPTION
**Pull request by hrithikwins**
Fixes the issue mentioned in https://github.com/MozillaReality/hubs-blender-exporter/issues/217

### CODE REVIEW

**Comment by hrithikwins** [comment]
image

**Review by keianhzo — COMMENTED** [review]
Not sure if "Only Horizontal" is preferred over the proposed "Vertical Axis Only". Any ideas @j-conrad @Exairnous ?

**Comment by hrithikwins** [comment]
Thanks @keianhzo @Exairnous @j-conrad for pointing out the wrong commits, now this is fixed with 
image

**Comment by Exairnous** [comment]
Thank you for the update @hrithikwins, this is looking much better!  We discussed in the add-on meeting that there should probably be a reference to it affecting the world space and removing the other rotational transforms, so what would you (and the others) think of adding "in world space and removes any other rotational transforms" to the end of the tooltip?

**Comment by hrithikwins** [comment]
Sure, so that would mean that the tooltip contains the text as 

Locks the Vertical Axis to enable only side to side movement in world space and removes any other rotational transforms

**Comment by Exairnous** [comment]
> Sure, so that would mean that the tooltip contains the text as
> 
> Locks the Vertical Axis to enable only side to side movement in world space and removes any other rotational transforms

Yes, that is what I'm suggesting :)

**Comment by hrithikwins** [comment]
Thanks Exairnous , the latest commit has the more descriptive description :)

**Comment by Exairnous** [comment]
Thank you Hrithik.

@keianhzo @j-conrad is everybody happy with the current wording?

**Comment by hrithikwins** [comment]
@keianhzo @j-conrad

**Review by keianhzo — APPROVED** [review]
LGTM! Thank you @hrithikwins

**Pull request merged**
