### PR TITLE
Fix typos, improve docs, and remove trailing periods.

### PR DESCRIPTION
**Pull request by Exairnous**
Fixed typos and grammar errors.
Added the full (mozilla.org) default URL to the video component (it was just https://). Improved the descriptions/tooltips to better document what the things do. Removed the trailing periods from descriptions/tooltips as Blender provides them for us and will cause duplicates if we provide them too. Periods aren't provided for labels, so those have been left.

### CODE REVIEW

**Comment by sarhugo** [comment]
Maybe here is a place to fix this? https://github.com/MozillaReality/hubs-blender-exporter/issues/77

**Comment by Exairnous** [comment]
@sarhugo Yup, Thank you!  That should definitely be in here!

**Comment by Exairnous** [comment]
Actually, I may have spoken too soon, this could be a little tricky because not just the display name and tooltip is misspelled.  I think the Hubs client would have to be modified to accept the new spelling for the component name as well, plus we'll need to provide a migration for old blend files.  All that to say that it's probably too big for this PR, unless we want to keep the component name and just fix the display name and tooltip.  @keianhzo What are your thoughts on this, should we wait and do everything in a new PR or should I add in a fix for the display stuff only and we can address the component name (or not) later?

**Comment by keianhzo** [comment]
Not super concerned about the misspelled `frustrum` component name as long as the user facing text is correct so I'm ok with just fixing that for now.

**Review by keianhzo — APPROVED** [review]
LGTM

**Pull request merged**
